/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.meituan.dorado.test.thrift.apitwitter;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TwitterIdlConstants {

  public static final int DEFAULT_AGE = 18;

}
