/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.meituan.dorado.codec.octo.meta;


public enum MessageType implements org.apache.thrift.TEnum {
  Normal(0),
  NormalHeartbeat(1),
  ScannerHeartbeat(2);

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MessageType findByValue(int value) { 
    switch (value) {
      case 0:
        return Normal;
      case 1:
        return NormalHeartbeat;
      case 2:
        return ScannerHeartbeat;
      default:
        return null;
    }
  }
}
